#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'bin2bcd_soc' in
 * file '../build/bin2bcd_soc.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following master:
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'bin2bcd_mm_periph_0', class 'bin2bcd_mm_periph'
 * The macros are prefixed with 'BIN2BCD_MM_PERIPH_0_'.
 * The prefix is the slave descriptor.
 */
#define BIN2BCD_MM_PERIPH_0_COMPONENT_TYPE bin2bcd_mm_periph
#define BIN2BCD_MM_PERIPH_0_COMPONENT_NAME bin2bcd_mm_periph_0
#define BIN2BCD_MM_PERIPH_0_BASE 0x0
#define BIN2BCD_MM_PERIPH_0_SPAN 32
#define BIN2BCD_MM_PERIPH_0_END 0x1f


#endif /* _ALTERA_HPS_0_H_ */
