# TCL File Generated by Component Editor 18.1
# Mon Aug 31 18:26:53 BST 2026
# DO NOT MODIFY


# 
# bin2bcd_mm_periph "bin2bcd_mm_periph" v1.0
# Olaoluwa Raji 2026.08.31.18:26:53
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module bin2bcd_mm_periph
# 
set_module_property DESCRIPTION ""
set_module_property NAME bin2bcd_mm_periph
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Olaoluwa Raji"
set_module_property DISPLAY_NAME bin2bcd_mm_periph
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL bin2bcd_mm
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file bin2bcd.sv SYSTEM_VERILOG PATH ../rtl/bin2bcd.sv
add_fileset_file bin2bcd_mm.sv SYSTEM_VERILOG PATH ../rtl/bin2bcd_mm.sv TOP_LEVEL_FILE
add_fileset_file counter.sv SYSTEM_VERILOG PATH ../rtl/counter.sv
add_fileset_file pkg.sv SYSTEM_VERILOG PATH ../rtl/pkg.sv


# 
# parameters
# 
add_parameter WORD_LEN NATURAL 32 ""
set_parameter_property WORD_LEN DEFAULT_VALUE 32
set_parameter_property WORD_LEN DISPLAY_NAME WORD_LEN
set_parameter_property WORD_LEN WIDTH ""
set_parameter_property WORD_LEN TYPE NATURAL
set_parameter_property WORD_LEN UNITS None
set_parameter_property WORD_LEN ALLOWED_RANGES 0:2147483647
set_parameter_property WORD_LEN DESCRIPTION ""
set_parameter_property WORD_LEN HDL_PARAMETER true
add_parameter ADDR_LEN NATURAL 3 ""
set_parameter_property ADDR_LEN DEFAULT_VALUE 3
set_parameter_property ADDR_LEN DISPLAY_NAME ADDR_LEN
set_parameter_property ADDR_LEN WIDTH ""
set_parameter_property ADDR_LEN TYPE NATURAL
set_parameter_property ADDR_LEN UNITS None
set_parameter_property ADDR_LEN ALLOWED_RANGES 0:2147483647
set_parameter_property ADDR_LEN DESCRIPTION ""
set_parameter_property ADDR_LEN HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset_n
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 write_n write_n Input 1
add_interface_port avalon_slave_0 read_n read_n Input 1
add_interface_port avalon_slave_0 address address Input ADDR_LEN
add_interface_port avalon_slave_0 writedata writedata Input WORD_LEN
add_interface_port avalon_slave_0 readdata readdata Output WORD_LEN
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset_n
# 
add_interface reset_n reset end
set_interface_property reset_n associatedClock clock
set_interface_property reset_n synchronousEdges DEASSERT
set_interface_property reset_n ENABLED true
set_interface_property reset_n EXPORT_OF ""
set_interface_property reset_n PORT_NAME_MAP ""
set_interface_property reset_n CMSIS_SVD_VARIABLES ""
set_interface_property reset_n SVD_ADDRESS_GROUP ""

add_interface_port reset_n rst_n reset_n Input 1

